"""add session status

Revision ID: 79a620516cab
Revises: eccff0c16a35
Create Date: 2026-07-09 07:52:51.393108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a620516cab'
down_revision: Union[str, None] = 'eccff0c16a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###


def upgrade() -> None:
    # 1. Add the new column with a default value so existing records default to 'active'
    op.add_column(
        'sessions', 
        sa.Column('status', sa.String(length=30), server_default='active', nullable=False)
    )
    
    # 2. Add the constraint to prevent invalid state strings
    op.create_check_constraint(
        'sessions_status_check',
        'sessions',
        "status IN ('active', 'summarization_pending', 'summarized')"
    )


def downgrade() -> None:
    # 1. Drop the constraint
    op.drop_constraint('sessions_status_check', 'sessions', type_='check')
    
    # 2. Drop the column
    op.drop_column('sessions', 'status')
